# Generated by Django 3.0.2 on 2021-01-14 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
