# Generated by Django 3.0.2 on 2021-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scapp', '0002_searchdata_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdchannel',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube チャンネルタイトル'),
        ),
        migrations.AlterField(
            model_name='holdchannel',
            name='channel_yid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube チャンネルID'),
        ),
        migrations.AlterField(
            model_name='holdchannel',
            name='now_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube 収集中のトークン'),
        ),
        migrations.AlterField(
            model_name='holdchannel',
            name='playList_yid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube playlistID'),
        ),
        migrations.AlterField(
            model_name='holdchannel',
            name='video_yid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube コメント収集中のvideoID'),
        ),
        migrations.AlterField(
            model_name='searchdata',
            name='channel_yid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube チャンネルID'),
        ),
    ]
