# Generated by Django 3.0.2 on 2021-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scapp', '0003_auto_20210114_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdchannel',
            name='status',
            field=models.IntegerField(verbose_name='0:確認待ち,1:動画収集中,2:コメント収集中,3:計算中'),
        ),
        migrations.AlterField(
            model_name='holdchannel',
            name='video_yid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='youtube コメント収集中のID'),
        ),
        migrations.AlterField(
            model_name='searchdata',
            name='status',
            field=models.IntegerField(verbose_name='0:ない, 1:ある'),
        ),
    ]
